<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FinanceService.Infrastructure\FinanceService.Infrastructure.csproj" />
        <ProjectReference Include="..\Shared.Presentation\Shared.Presentation.csproj" />
    </ItemGroup>

</Project>